//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Branch
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Branch()
    {
        this.Managers = new HashSet<Manager>();
        this.Products = new HashSet<Product>();
    }

    public int Branch_ID { get; set; }
    public string Location { get; set; }
    public string BranchType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Manager> Managers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Cart
{
    public int Cart_ID { get; set; }
    public Nullable<int> Order_ID { get; set; }
    public Nullable<int> Product_ID { get; set; }
    public string User_ID { get; set; }
    public Nullable<int> Amount { get; set; }
    public Nullable<System.DateTime> Date_Purchased { get; set; }
    public Nullable<bool> Is_In_Cart { get; set; }

    public virtual Product Product { get; set; }
}

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.Orders = new HashSet<Order>();
        this.Repairs = new HashSet<Repair>();
    }

    public int Customer_ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string BillAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Repair> Repairs { get; set; }
}

public partial class Image
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Image()
    {
        this.Products = new HashSet<Product>();
    }

    public int Image_ID { get; set; }
    public string Description { get; set; }
    public string FilePath { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Manager
{
    public int Manager_ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public Nullable<int> Branch_ID { get; set; }
    public string User_ID { get; set; }

    public virtual Branch Branch { get; set; }
}

public partial class Order
{
    public int Order_ID { get; set; }
    public Nullable<int> Customer_ID { get; set; }
    public Nullable<int> Product_ID { get; set; }
    public Nullable<int> Transaction_ID { get; set; }
    public Nullable<int> Payment_ID { get; set; }
    public Nullable<int> Reserve_Key { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<decimal> Subtotal { get; set; }
    public Nullable<decimal> VAT { get; set; }
    public Nullable<decimal> Total { get; set; }
    public Nullable<bool> DeliveryFlag { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual Product Product { get; set; }
    public virtual Transaction Transaction { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.Carts = new HashSet<Cart>();
        this.Orders = new HashSet<Order>();
    }

    public int Product_ID { get; set; }
    public Nullable<int> Branch_ID { get; set; }
    public Nullable<int> ProductType_ID { get; set; }
    public Nullable<int> Image_ID { get; set; }
    public decimal Subtotal { get; set; }
    public decimal VAT { get; set; }
    public decimal Total { get; set; }
    public string Material { get; set; }
    public string Description { get; set; }
    public string Watch_Series { get; set; }
    public string Watch_ModelYear { get; set; }
    public string Watch_Style { get; set; }
    public string Watch_Movement { get; set; }
    public string Watch_DialType { get; set; }
    public string Watch_WaterResistance { get; set; }
    public string Jewel_Size { get; set; }
    public int Quantity { get; set; }
    public bool Is_Available { get; set; }
    public bool Is_Visible { get; set; }

    public virtual Branch Branch { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
    public virtual Image Image { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
    public virtual ProductType ProductType { get; set; }
}

public partial class ProductType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductType()
    {
        this.Products = new HashSet<Product>();
    }

    public int ProductType_ID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Repair
{
    public int Repair_ID { get; set; }
    public Nullable<int> Customer_ID { get; set; }
    public Nullable<System.DateTime> DateStart { get; set; }
    public Nullable<System.DateTime> DateEnd { get; set; }
    public Nullable<decimal> Subtotal { get; set; }
    public Nullable<decimal> VAT { get; set; }
    public Nullable<decimal> Total { get; set; }
    public Nullable<bool> DeliveryFlag { get; set; }
    public string Status { get; set; }

    public virtual Customer Customer { get; set; }
}

public partial class Transaction
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transaction()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Transaction_ID { get; set; }
    public Nullable<int> Order_ID { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Description { get; set; }
    public string Comment { get; set; }
    public Nullable<decimal> Subtotal { get; set; }
    public Nullable<decimal> VAT { get; set; }
    public Nullable<decimal> Total { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
}
