//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Battery
{
    public System.Guid Battery_ID { get; set; }
    public Nullable<System.Guid> Branch_ID { get; set; }
    public string Battery1 { get; set; }
}

public partial class Branch
{
    public System.Guid Branch_ID { get; set; }
    public string Branch_Location { get; set; }
}

public partial class Cart
{
    public System.Guid Purchase_ID { get; set; }
    public Nullable<System.Guid> Transaction_ID { get; set; }
    public Nullable<System.Guid> Product_ID { get; set; }
    public Nullable<System.Guid> Client_ID { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public Nullable<System.DateTime> Date_Purchased { get; set; }
    public string Is_In_Cart { get; set; }
}

public partial class Extra
{
    public System.Guid Extra_ID { get; set; }
    public Nullable<System.Guid> Branch_ID { get; set; }
    public string Extra1 { get; set; }
}

public partial class OrderItem
{
    public System.Guid Order_ID { get; set; }
    public Nullable<System.Guid> Watch_ID { get; set; }
}

public partial class Pin
{
    public System.Guid Pin_ID { get; set; }
    public Nullable<System.Guid> Branch_ID { get; set; }
    public string Extra { get; set; }
}

public partial class Product
{
    public System.Guid Product_ID { get; set; }
    public Nullable<System.Guid> ProductType_ID { get; set; }
    public Nullable<System.Guid> Purchase_ID { get; set; }
    public Nullable<System.Guid> Watch_ID { get; set; }
    public Nullable<System.Guid> Strap_ID { get; set; }
    public string Name { get; set; }
    public Nullable<decimal> Price { get; set; }
    public string Description { get; set; }
    public byte[] Image { get; set; }
}

public partial class ProductType
{
    public System.Guid ProductType_ID { get; set; }
    public Nullable<System.Guid> Product_ID { get; set; }
    public string Name { get; set; }
}

public partial class Repair
{
    public System.Guid Repair_ID { get; set; }
    public Nullable<System.Guid> RepairStatus_ID { get; set; }
    public Nullable<System.DateTime> Repair_DateStart { get; set; }
    public Nullable<System.DateTime> Repair_DateEnd { get; set; }
    public Nullable<decimal> Repair_Subtotal { get; set; }
    public Nullable<decimal> Repair_VAT { get; set; }
    public Nullable<decimal> Repair_Total { get; set; }
    public string Repair_DeliveryFlag { get; set; }
}

public partial class Strap
{
    public System.Guid Strap_ID { get; set; }
    public Nullable<System.Guid> Branch_ID { get; set; }
    public string Strap1 { get; set; }
}

public partial class Transaction
{
    public System.Guid Transaction_ID { get; set; }
    public Nullable<System.Guid> Purchase_ID { get; set; }
    public Nullable<System.DateTime> Transaction_Date { get; set; }
    public string Transaction_Description { get; set; }
    public string Transaction_Comment { get; set; }
    public Nullable<decimal> Transaction_Subtotal { get; set; }
    public Nullable<decimal> Transaction_VAT { get; set; }
    public Nullable<decimal> Transaction_Total { get; set; }
}

public partial class Watch
{
    public System.Guid Watch_ID { get; set; }
    public Nullable<System.Guid> Branch_ID { get; set; }
    public Nullable<decimal> Watch_Price { get; set; }
    public string Watch_Make { get; set; }
    public string Watch_Series { get; set; }
    public Nullable<System.DateTime> Watch_ModelYear { get; set; }
    public string Watch_Style { get; set; }
    public string Watch_Movement { get; set; }
    public string Watch_CaseMaterial { get; set; }
    public string Watch_DialType { get; set; }
    public string Watch_WaterResistance { get; set; }
    public string Watch_BraceletMaterial { get; set; }
    public string Watch_Functions { get; set; }
    public byte[] Watch_Image { get; set; }
}
