//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Battery
{
    public int Battery_ID { get; set; }
    public int Branch_ID { get; set; }
    public string Battery1 { get; set; }

    public virtual Branch Branch { get; set; }
}

public partial class Branch
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Branch()
    {
        this.Batteries = new HashSet<Battery>();
        this.Extras = new HashSet<Extra>();
        this.Items = new HashSet<Item>();
        this.Pins = new HashSet<Pin>();
        this.Straps = new HashSet<Strap>();
    }

    public int Branch_ID { get; set; }
    public string Location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Battery> Batteries { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Extra> Extras { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Item> Items { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Pin> Pins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Strap> Straps { get; set; }
}

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.OrderItems = new HashSet<OrderItem>();
        this.Repairs = new HashSet<Repair>();
    }

    public int Customer_ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Address { get; set; }
    public Nullable<int> Phone_Number { get; set; }
    public Nullable<System.DateTime> Next_Repair_Date { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderItem> OrderItems { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Repair> Repairs { get; set; }
}

public partial class Extra
{
    public int Extra_ID { get; set; }
    public int Branch_ID { get; set; }
    public string Extra1 { get; set; }

    public virtual Branch Branch { get; set; }
}

public partial class Item
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {
        this.OrderItems = new HashSet<OrderItem>();
    }

    public int Item_ID { get; set; }
    public int Branch_ID { get; set; }
    public float Price { get; set; }
    public string Make { get; set; }
    public string Series { get; set; }
    public Nullable<int> Model_Year { get; set; }
    public string Style { get; set; }
    public string Movement { get; set; }
    public string Case_Material { get; set; }
    public string Dial_Type { get; set; }
    public string Water_Resistance { get; set; }
    public string Bracelet_Material { get; set; }
    public string Functions { get; set; }
    public string Image { get; set; }

    public virtual Branch Branch { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderItem> OrderItems { get; set; }
}

public partial class OrderItem
{
    public int Customer_ID { get; set; }
    public int Order_ID { get; set; }
    public int Item_ID { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual Item Item { get; set; }
    public virtual Transaction Transaction { get; set; }
}

public partial class Pin
{
    public int Pin_ID { get; set; }
    public int Branch_ID { get; set; }
    public string Pin1 { get; set; }

    public virtual Branch Branch { get; set; }
}

public partial class Repair
{
    public int Repair_ID { get; set; }
    public int Customer_ID { get; set; }
    public int RepairStatus_ID { get; set; }
    public System.DateTime Start_Date { get; set; }
    public System.DateTime End_Date { get; set; }
    public float Subtotal { get; set; }
    public float VAT { get; set; }
    public float Total { get; set; }
    public byte[] Delivery_Flag { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual RepairStatu RepairStatu { get; set; }
}

public partial class RepairStatu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RepairStatu()
    {
        this.Repairs = new HashSet<Repair>();
    }

    public int RepairStatus_ID { get; set; }
    public string RepairStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Repair> Repairs { get; set; }
}

public partial class Strap
{
    public int Battery_ID { get; set; }
    public int Branch_ID { get; set; }
    public string Strap1 { get; set; }

    public virtual Branch Branch { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Transaction
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transaction()
    {
        this.OrderItems = new HashSet<OrderItem>();
    }

    public int Transaction_ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Description { get; set; }
    public string Comment { get; set; }
    public Nullable<float> Subtotal { get; set; }
    public float VAT { get; set; }
    public float Total { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderItem> OrderItems { get; set; }
}
